// Code your design here
// SPI write operation

module spi_state(
  input wire clk, // system generated clock
  input wire reset, // Asychronous RESET
  
  input wire [15:0] data_in, // data to send/write to slave
  output wire spi_sclk, // clock generated by master
  output wire spi_data, // MOSI Line
  output wire spi_cs_l, // active low chip select
  output reg [4:0] counter
);
  
  reg [15:0] MOSI; // SPI shift register, sending data from master from this line.
  reg [4:0] count; // control counter, Counting data bit from 16 to 0 to send one by one;
  reg cs_l; // active low chip select
  reg sclk;
  reg [2:0] state;
  
  initial begin
    $monitor("MOSI = %0d | COUNT = %0d ", MOSI, count);
  end
  
  
  always @(posedge clk or posedge reset) begin
    if(reset) begin //RESET state, resetting all reg to zero and making the clock count to 16
      MOSI <= 16'b0;
      count <= 5'd16;
      cs_l <= 1'b1;
      sclk <= 1'b0;
    end else begin
      case(state)
        0: begin // IDLE State
          sclk <= 1'b0;
          cs_l <= 1'b0;
          state <= 1;
        end
        1: begin // Data sending 
          sclk <= 1'b0;
          cs_l <= 1'b0;
          MOSI <= data_in[count - 1];
          count <= count - 1;
          state <= 2;
        end
        2: begin // Counter updation state
          sclk <= 1'b1;
          if(count > 0) begin
            state <= 1;
          end else begin
            count <= 16;
          end
          state <= 0;
        end
        
        default: state <= 0;
      endcase
    end
  end
    
    assign spi_cs_l = cs_l;
    assign spi_sclk = sclk;
    assign spi_data = MOSI;
    assign counter = count;
    
endmodule
